// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACCixSx514fmAJOKLxjOjXlvJ4KAqxWYQ',
    appId: '1:467014466979:web:4814f1c07ff7449dac2e16',
    messagingSenderId: '467014466979',
    projectId: 'eduscale-push-notification',
    authDomain: 'eduscale-push-notification.firebaseapp.com',
    storageBucket: 'eduscale-push-notification.firebasestorage.app',
    measurementId: 'G-CZVLJ673GJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPN_IZp342wXlgne1wpDb6VMmvexZdG30',
    appId: '1:467014466979:android:5c0323e03e9be864ac2e16',
    messagingSenderId: '467014466979',
    projectId: 'eduscale-push-notification',
    storageBucket: 'eduscale-push-notification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbOjuz_hTPOTWcOqdMvwO6YrFZ6MuEL68',
    appId: '1:467014466979:ios:27dbe8d3e9119846ac2e16',
    messagingSenderId: '467014466979',
    projectId: 'eduscale-push-notification',
    storageBucket: 'eduscale-push-notification.firebasestorage.app',
    iosBundleId: 'com.example.eduScale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbOjuz_hTPOTWcOqdMvwO6YrFZ6MuEL68',
    appId: '1:467014466979:ios:27dbe8d3e9119846ac2e16',
    messagingSenderId: '467014466979',
    projectId: 'eduscale-push-notification',
    storageBucket: 'eduscale-push-notification.firebasestorage.app',
    iosBundleId: 'com.example.eduScale',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACCixSx514fmAJOKLxjOjXlvJ4KAqxWYQ',
    appId: '1:467014466979:web:1f025ba5aba51402ac2e16',
    messagingSenderId: '467014466979',
    projectId: 'eduscale-push-notification',
    authDomain: 'eduscale-push-notification.firebaseapp.com',
    storageBucket: 'eduscale-push-notification.firebasestorage.app',
    measurementId: 'G-2V4FXQMZGC',
  );
}
