-- WELCOME TO EDU-SCALE DATABASE SCHEMA
-- THIS SCHEMA IS FOR 1.0.2 VERSION
-- NOTE: competition schema is under development
-- TO-FIX: (library_resources) table should convert status from pendding to pending in bith supabase and flutter
-- TO-FIX: (schools) table should convert status from suspended to banned in bith supabase and flutter
-- TO-FIX: (users) table should convert status from pending to banned in bith supabase and flutter
-- TO-FIX: (competion schema) needs to be re-written  

-- ==========================================================
-- PLATFORM LAYER - [SYSTEM]
-- ==========================================================

CREATE TABLE schools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    school_domain VARCHAR(50) UNIQUE NOT NULL, -- same as email domain
    name VARCHAR(100) NOT NULL,
    address VARCHAR(255) NOT NULL,
    logo_url TEXT,
    school_weekend VARCHAR(50)[] DEFAULT ARRAY[]::VARCHAR(50)[] NOT NULL, -- EX: ['Sat', 'Fri']
    educational_system VARCHAR(36) CHECK (educational_system IN ('Private National','American', 'IGCSE', 'IB', 'Other')) NOT NULL,
    class_max_capacity INT DEFAULT 25, 
    status VARCHAR(36) DEFAULT 'suspended' CHECK (status IN ('active','suspended','deleted')), -- suspended (means not set up yet), deleted (means the school was a client but they left forever)
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE school_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(255) NOT NULL,
    price_per_user INT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE school_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    school_id BIGINT NOT NULL,
    plan_id BIGINT NOT NULL,
    users_limit INT NOT NULL, -- The number of users school purchased
    library_limit_in_gb INT NOT NULL, -- The total size of the files the school pushased in GB
    start_at DATE NOT NULL,
    end_at DATE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (school_id) REFERENCES schools(id),
    FOREIGN KEY (plan_id) REFERENCES school_plans(id)
);



-- ==========================================================
-- SCHOOL STRUCTURE LAYER - [SYSTEM]
-- ==========================================================

CREATE TABLE grades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    school_id BIGINT NOT NULL,
    name VARCHAR(50) CHECK (name IN ('Grade 1', 'Grade 2', 'Grade 3', 'Grade 4', 'Grade 5', 'Grade 6', 'Grade 7', 'Grade 8', 'Grade 9', 'Grade 10', 'Grade 11', 'Grade 12')) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (school_id) REFERENCES schools(id)
);

CREATE TABLE classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    school_id BIGINT NOT NULL,
    grade_id BIGINT NOT NULL,
    name VARCHAR(50) CHECK (name IN ('Class A', 'Class B', 'Class C', 'Class D', 'Class E', 'Class F', 'Class G', 'Class H', 'Class I', 'Class J')) NOT NULL, 
    nickname VARCHAR(50) NOT NULL, -- we usually set it same as name for first time
    max_capacity INT DEFAULT 25,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (school_id) REFERENCES schools(id),
    FOREIGN KEY (grade_id) REFERENCES grades(id)
);


CREATE TABLE subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    school_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL, -- Too many subjects can found so we can not add CHECK constraint here.
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (school_id) REFERENCES schools(id)
);



-- ==========================================================
-- USERS LAYER - [SYSTEM]
-- ==========================================================

CREATE TABLE users (
    id UUID UNIQUE PRIMARY KEY NOT NULL, -- same uuid in auth.users table 
    school_id BIGINT NOT NULL,
    role VARCHAR(20) CHECK (role IN ('admin', 'teacher', 'student', 'parent')) NOT NULL, -- this is not for authorization, its just for filtering users and targting them in easy way 
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    avatar_url TEXT, -- avatars are png files hosted in github to reduces app size
    phone VARCHAR(50),
    status VARCHAR(50) DEFAULT 'pending' CHECK (status IN ('active', 'pending', 'suspended')) NOT NULL, -- active, pending (invited but not registered yet), suspended (suspended by school admin or edu-scale team)
    gender VARCHAR(20) CHECK (gender IN ('male', 'female')),
    birthday DATE,
    fcm_token TEXT,
    -- national_id VARCHAR(50),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (school_id) REFERENCES schools(id)
);

CREATE TABLE user_profiles (
    user_id UUID PRIMARY KEY NOT NULL, -- same uuid in auth.users table and public.users table
    grade_id BIGINT,
    class_id BIGINT,
    subject_id BIGINT,
    parent_id UUID,
    student_id UUID,
    extra JSON,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (grade_id) REFERENCES grades(id),
    FOREIGN KEY (class_id) REFERENCES classes(id),
    FOREIGN KEY (subject_id) REFERENCES subjects(id),
    FOREIGN KEY (parent_id) REFERENCES users(id),
    FOREIGN KEY (student_id) REFERENCES users(id)
);



-- ==========================================================
-- SYSTEM APPENDIXES LAYERS - [SYSTEM]
-- ==========================================================

CREATE TABLE ads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    title VARCHAR(36) NOT NULL,
    content VARCHAR(255) NOT NULL,
    image_url TEXT NOT NULL,
    cta_url TEXT, -- can be null if we do not need cta
    start_at DATE NOT NULL,
    end_at DATE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ad_target_by_school (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    school_id BIGINT NOT NULL,
    ad_id BIGINT NOT NULL,
    FOREIGN KEY (school_id) REFERENCES schools(id),
    FOREIGN KEY (ad_id) REFERENCES ads(id)
);

CREATE TABLE ad_target_by_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    ad_id BIGINT NOT NULL,
    role VARCHAR(20) CHECK (role IN ('admin', 'teacher', 'student', 'parent')) NOT NULL,
    FOREIGN KEY (ad_id) REFERENCES ads(id)
);

CREATE TABLE ad_target_by_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    ad_id BIGINT NOT NULL, 
    user_id UUID NOT NULL,
    FOREIGN KEY (ad_id) REFERENCES ads(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE ad_target_by_grade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    ad_id BIGINT NOT NULL, 
    grade_id BIGINT NOT NULL,
    FOREIGN KEY (ad_id) REFERENCES ads(id),
    FOREIGN KEY (grade_id) REFERENCES grades(id)
);

CREATE TABLE ad_target_by_class (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    ad_id BIGINT NOT NULL, 
    class_id BIGINT NOT NULL,
    FOREIGN KEY (ad_id) REFERENCES ads(id),
    FOREIGN KEY (class_id) REFERENCES classes(id)
);


CREATE TABLE support_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    school_id BIGINT NOT NULL,
    user_id UUID NOT NULL,
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL, 
    status VARCHAR(50) CHECK (status IN ('opened', 'in_progress', 'closed')) NOT NULL,
    label VARCHAR(50) CHECK (label IN ('bug', 'issue', 'other')) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (school_id) REFERENCES schools(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE support_tickets_replies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    school_id BIGINT NOT NULL,
    support_ticket_id BIGINT NOT NULL,
    user_id UUID NOT NULL,
    user_replier_role VARCHAR(50) CHECK (user_replier_role IN ('admin', 'edu-scale-team')) NOT NULL, -- soon will be IT
    reply TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (school_id) REFERENCES schools(id),
    FOREIGN KEY (support_ticket_id) REFERENCES support_tickets(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);


CREATE TABLE contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    school_id BIGINT NOT NULL,
    user_id UUID NOT NULL,
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    reason VARCHAR(50) CHECK (reason IN ('suggest_feature', 'edit_feature', 'other')) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (school_id) REFERENCES schools(id)
);




-- ==========================================================
-- ASSIGNMENTS - [FEATURE]
-- ==========================================================

CREATE TABLE assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    school_id BIGINT NOT NULL,
    teacher_id UUID NOT NULL,
    subject_id BIGINT NOT NULL,
    grade_id BIGINT NOT NULL,
    class_id BIGINT, -- if null, it means the assignment is for the whole grade
    topic VARCHAR(255) NOT NULL,
    publish_status VARCHAR(50) CHECK (publish_status IN ('published', 'unpublished')) NOT NULL,
    number_of_questions INT CHECK (number_of_questions BETWEEN 1 AND 20) NOT NULL,
    due_date TIMESTAMPTZ NOT NULL, -- if due date passed then the assignment is past assignment and students can not submit anymore
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (school_id) REFERENCES schools(id),
    FOREIGN KEY (teacher_id) REFERENCES users(id),
    FOREIGN KEY (subject_id) REFERENCES subjects(id),
    FOREIGN KEY (grade_id) REFERENCES grades(id),
    FOREIGN KEY (class_id) REFERENCES classes(id)
);

CREATE TABLE assignment_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    school_id BIGINT NOT NULL,
    assignment_id BIGINT NOT NULL,
    question_order INT NOT NULL, -- the order of the question in the assignment, starts from 1 to number_of_questions
    question_text TEXT NOT NULL,
    options_1 VARCHAR(255) NOT NULL,
    options_2 VARCHAR(255) NOT NULL,
    options_3 VARCHAR(255),
    options_4 VARCHAR(255),
    options_5 VARCHAR(255),
    options_6 VARCHAR(255),
    model_answer VARCHAR(255) NOT NULL,
    FOREIGN KEY (school_id) REFERENCES schools(id),
    FOREIGN KEY (assignment_id) REFERENCES assignments(id)
);


CREATE TABLE assignment_student_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    school_id BIGINT NOT NULL,
    student_id UUID NOT NULL,
    assignment_id BIGINT NOT NULL,
    number_of_correct_questions INT DEFAULT 0 NOT NULL,
    total_number_of_questions INT DEFAULT 0 NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (school_id) REFERENCES schools(id),
    FOREIGN KEY (assignment_id) REFERENCES assignments(id),
    FOREIGN KEY (student_id) REFERENCES users(id)
);

CREATE TABLE assignment_student_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    school_id BIGINT NOT NULL,
    submission_id BIGINT NOT NULL,
    assignment_question_id BIGINT NOT NULL,
    answer VARCHAR(255) NOT NULL, -- student answer
    is_correct BOOLEAN DEFAULT FALSE NOT NULL,
    FOREIGN KEY (school_id) REFERENCES schools(id),
    FOREIGN KEY (submission_id) REFERENCES assignment_student_submissions(id),
    FOREIGN KEY (assignment_question_id) REFERENCES assignment_questions(id)
);



-- ==========================================================
-- QUIZZES - [FEATURE]
-- ==========================================================

CREATE TABLE quizzes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    school_id BIGINT NOT NULL,
    teacher_id UUID NOT NULL,
    subject_id BIGINT NOT NULL,
    grade_id BIGINT NOT NULL,
    class_id BIGINT, -- if null, it means the quiz is for the whole grade
    topic VARCHAR(255) NOT NULL,
    publish_status VARCHAR(50) CHECK (publish_status IN ('published', 'unpublished')) NOT NULL,
    number_of_questions INT CHECK (number_of_questions BETWEEN 1 AND 20) NOT NULL,
    -- quiz_timer_in_muints INT NOT NULL,
    -- quiz_start_at TIMESTAMPTZ NOT NULL,
    quiz_start_at TIMESTAMPTZ NOT NULL,
    due_date TIMESTAMPTZ NOT NULL, -- if due date passed then the quiz is past quiz and students can not submit anymore (quiz_timer = due_date - quiz_start_at)
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (school_id) REFERENCES schools(id),
    FOREIGN KEY (teacher_id) REFERENCES users(id),
    FOREIGN KEY (subject_id) REFERENCES subjects(id),
    FOREIGN KEY (grade_id) REFERENCES grades(id),
    FOREIGN KEY (class_id) REFERENCES classes(id)
);

CREATE TABLE quiz_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    school_id BIGINT NOT NULL,
    quiz_id BIGINT NOT NULL,
    question_order INT NOT NULL, -- the order of the question in the quiz, starts from 1 to number_of_questions
    question_text TEXT NOT NULL,
    options_1 VARCHAR(255) NOT NULL,
    options_2 VARCHAR(255) NOT NULL,
    options_3 VARCHAR(255),
    options_4 VARCHAR(255),
    options_5 VARCHAR(255),
    options_6 VARCHAR(255),
    model_answer VARCHAR(255) NOT NULL,
    FOREIGN KEY (school_id) REFERENCES schools(id),
    FOREIGN KEY (quiz_id) REFERENCES quizzes(id)
);


CREATE TABLE quiz_student_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    school_id BIGINT NOT NULL,
    student_id UUID NOT NULL,
    quiz_id BIGINT NOT NULL,
    number_of_correct_questions INT DEFAULT 0,
    total_number_of_questions INT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (school_id) REFERENCES schools(id),
    FOREIGN KEY (student_id) REFERENCES users(id),
    FOREIGN KEY (quiz_id) REFERENCES quizzes(id)
);

CREATE TABLE quiz_student_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    school_id BIGINT NOT NULL,
    submission_id BIGINT NOT NULL,
    quiz_question_id BIGINT NOT NULL,
    answer VARCHAR(255) NOT NULL, -- student answer
    is_correct BOOLEAN DEFAULT FALSE NOT NULL,
    FOREIGN KEY (school_id) REFERENCES schools(id),
    FOREIGN KEY (submission_id) REFERENCES quiz_student_submissions(id),
    FOREIGN KEY (quiz_question_id) REFERENCES quiz_questions(id)
);

-- ==========================================================
-- LIBRARY - [FEATURE]
-- ==========================================================

CREATE TABLE library_resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    school_id BIGINT NOT NULL,
    teacher_id UUID NOT NULL,
    subject_id BIGINT NOT NULL,
    grade_id BIGINT NOT NULL,
    class_id BIGINT, -- if null, it means the resource is for the whole grade
    title VARCHAR(255) NOT NULL,
    file_url TEXT NOT NULL,
    file_size_in_kb INT NOT NULL,
    file_type VARCHAR(36) CHECK (file_type IN ('pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'png', 'jpg')) NOT NULL,
    status VARCHAR(36) DEFAULT 'pendding' CHECK (status IN ('approved', 'pendding', 'rejected')) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (school_id) REFERENCES schools(id),
    FOREIGN KEY (teacher_id) REFERENCES users(id),
    FOREIGN KEY (subject_id) REFERENCES subjects(id),
    FOREIGN KEY (grade_id) REFERENCES grades(id),
    FOREIGN KEY (class_id) REFERENCES classes(id) 
);



-- ==========================================================
-- COMMUNITY CHAT - [FEATURE]
-- ==========================================================

CREATE TABLE channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    school_id BIGINT NOT NULL,
    grade_id BIGINT, -- if null, it means the channel is for the whole school
    class_id BIGINT, -- if null, it means the channel is for the whole grade + do not forget to access the class nickname to display it
    FOREIGN KEY (school_id) REFERENCES schools(id),
    FOREIGN KEY (grade_id) REFERENCES grades(id),
    FOREIGN KEY (class_id) REFERENCES classes(id)
);

CREATE TABLE channel_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    channel_id BIGINT NOT NULL,
    sender_id UUID NOT NULL,
    attached_assignment_id BIGINT, -- if the message is sent with an assignment, it will be stored here, otherwise it will be null
    attached_quiz_id BIGINT, -- if the message is sent with a quiz, it will be stored here, otherwise it will be null
    -- library_id BIGINT, --SOON
    -- competition_id BIGINT, -- SOON
    -- time_table_id BIGINT, -- SOON
    -- event_id BIGINT, -- SOON
    message_text TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (channel_id) REFERENCES channels(id),
    FOREIGN KEY (sender_id) REFERENCES users(id),
    FOREIGN KEY (attached_assignment_id) REFERENCES assignments(id),
    FOREIGN KEY (attached_quiz_id) REFERENCES quizzes(id)
);

CREATE TABLE message_reads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    user_id UUID NOT NULL,
    message_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (message_id) REFERENCES channel_messages(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);



-- ==========================================================
-- COMPETITIONS - [FEATURE]
-- ==========================================================

CREATE TABLE competitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY, -- Join code is same as id
    school_id BIGINT NOT NULL,
    teacher_id UUID NOT NULL,
    title VARCHAR(255) NOT NULL,
    type VARCHAR(50) CHECK (type IN ('solo', 'team')) NOT NULL,
    question_timer_in_seconds INT DEFAULT 180 NOT NULL, -- the timer for each question
    number_of_questions INT CHECK (number_of_questions BETWEEN 1 AND 20) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (school_id) REFERENCES schools(id),
    FOREIGN KEY (teacher_id) REFERENCES users(id)
);

CREATE TABLE competition_choose_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    competition_id BIGINT NOT NULL,
    question_text TEXT NOT NULL,
    option_1 VARCHAR(255) NOT NULL,
    option_2 VARCHAR(255) NOT NULL,
    option_3 VARCHAR(255),
    option_4 VARCHAR(255),
    correct_answer VARCHAR(255) NOT NULL,
    style VARCHAR(50) CHECK (style IN ('shot', 'long', 'wheel')) NOT NULL,
    FOREIGN KEY (competition_id) REFERENCES competitions(id)
);


CREATE TABLE competition_teams_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    competition_id BIGINT NOT NULL,
    student_id_1 UUID NOT NULL,
    student_id_2 UUID,
    student_id_3 UUID,
    student_id_4 UUID,
    student_id_5 UUID,
    student_id_6 UUID,
    name VARCHAR(255) NOT NULL,
    points_earned INT DEFAULT 0,
    current_question INT DEFAULT 0,
    FOREIGN KEY (competition_id) REFERENCES competitions(id),
    FOREIGN KEY (student_id_1) REFERENCES users(id),
    FOREIGN KEY (student_id_2) REFERENCES users(id),
    FOREIGN KEY (student_id_3) REFERENCES users(id),
    FOREIGN KEY (student_id_4) REFERENCES users(id),
    FOREIGN KEY (student_id_5) REFERENCES users(id),
    FOREIGN KEY (student_id_6) REFERENCES users(id)
);


CREATE TABLE competition_solo_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    competition_id BIGINT NOT NULL,
    student_id UUID,
    points_earned INT DEFAULT 0,
    current_question INT DEFAULT 0,
    FOREIGN KEY (competition_id) REFERENCES competitions(id),
    FOREIGN KEY (student_id) REFERENCES users(id)
);


CREATE TABLE competition_student_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    school_id BIGINT NOT NULL,
    competition_id BIGINT NOT NULL,
    student_id UUID NOT NULL,
    grade_id BIGINT NOT NULL, -- essintial for admin to trace which grade is more active in competitions
    class_id BIGINT NOT NULL,
    play_type VARCHAR(50) CHECK (play_type IN ('solo', 'team')) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (school_id) REFERENCES schools(id),
    FOREIGN KEY (competition_id) REFERENCES competitions(id),
    FOREIGN KEY (student_id) REFERENCES users(id),
    FOREIGN KEY (grade_id) REFERENCES grades(id),
    FOREIGN KEY (class_id) REFERENCES classes(id)
);



-- ==========================================================
-- PRORESS - [FEATURE]
-- ==========================================================

CREATE TABLE user_progress (
    user_id UUID PRIMARY KEY NOT NULL,
    points INT DEFAULT 0 NOT NULL CHECK (points >= 0),
    current_streak INT DEFAULT 0 NOT NULL CHECK (current_streak >= 0),
    longest_streak INT DEFAULT 0 NOT NULL CHECK (longest_streak >= 0),
    last_streak_week DATE,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- NOTE: If you want to introduce a new badge for the system you need to check check_reward_badges() RPC in order to work proper
CREATE TABLE badges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    icon_url TEXT NOT NULL,
    category VARCHAR(50) NOT NULL,
    requirement VARCHAR(50) NOT NULL,
    requirement_value INT NOT NULL CHECK (requirement_value > 0),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_badges ( 
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    user_id UUID NOT NULL,
    badge_id BIGINT NOT NULL,
    earned_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (badge_id) REFERENCES badges(id)
);


-- ==========================================================
-- CALENDER - [FEATURE]
-- ==========================================================

CREATE TABLE timetable (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    school_id BIGINT NOT NULL,
    grade_id BIGINT NOT NULL,
    class_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    teacher_id UUID NOT NULL,
    day_of_week INT CHECK (day_of_week BETWEEN 1 AND 7) NOT NULL, -- 1 = Saterday, 7 = Friday
    start_at TIME NOT NULL,
    end_at TIME NOT NULL,
    room VARCHAR(100), -- if the school has multiple rooms EX: lab 1, computer room..etc, otherwise it can be null
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (school_id) REFERENCES schools(id),
    FOREIGN KEY (grade_id) REFERENCES grades(id),
    FOREIGN KEY (class_id) REFERENCES classes(id),
    FOREIGN KEY (subject_id) REFERENCES subjects(id),
    FOREIGN KEY (teacher_id) REFERENCES users(id)
);


CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    school_id BIGINT NOT NULL,
    created_by UUID NOT NULL,
    title VARCHAR(160) NOT NULL,
    description TEXT NOT NULL,
    day_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (school_id) REFERENCES schools(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
);


CREATE TABLE event_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    event_id BIGINT NOT NULL,
    grade_id BIGINT, -- if null, its for whole grade
    class_id BIGINT, -- if null, its for whole class
    subject_id BIGINT, -- if null, its for whole subject
    role VARCHAR(20) CHECK (role IN ('admin', 'teacher', 'student', 'parent')), -- if null, its for whole school
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (event_id) REFERENCES events(id),
    FOREIGN KEY (grade_id) REFERENCES grades(id),
    FOREIGN KEY (class_id) REFERENCES classes(id),
    FOREIGN KEY (subject_id) REFERENCES subjects(id)
);


CREATE TABLE attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    school_id BIGINT NOT NULL,
    grade_id BIGINT NOT NULL,
    class_id BIGINT NOT NULL,
    student_id UUID NOT NULL, -- the student that we are taking attendance for
    taken_by UUID NOT NULL, -- the teacher that takes the attendance
    attendance_date DATE NOT NULL, -- the day that we are taking attendance for
    status VARCHAR(20) CHECK (status IN ('present', 'absent', 'late', 'excused')) NOT NULL,
    reason VARCHAR(50), -- if the student is absent, late or excused, the teacher can add notes here to explain the reason. if null it means the student is present or the teacher did not add a reason
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (school_id) REFERENCES schools(id),
    FOREIGN KEY (grade_id) REFERENCES grades(id),
    FOREIGN KEY (class_id) REFERENCES classes(id),
    FOREIGN KEY (student_id) REFERENCES users(id),
    FOREIGN KEY (taken_by) REFERENCES users(id)
);



-- ==========================================================
-- MR EVERYTHING CHATS - [FEATURE]
-- ==========================================================

CREATE TABLE mr_everything_chats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    school_id BIGINT NOT NULL,
    user_id UUID NOT NULL,
    title VARCHAR(255) NOT NULL, -- auto-generated title by ai
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (school_id) REFERENCES schools(id)
);

CREATE TABLE mr_everything_chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    user_id UUID NOT NULL,
    sender VARCHAR(12) CHECK (sender IN ('user', 'ai')) NOT NULL,
    message_text TEXT NOT NULL,
    assignment_questions_id BIGINT, -- if the message is sent with an assignment question, it will be stored here, otherwise it will be null
    quiz_questions_id BIGINT, -- if the message is sent with a quiz question, it will be stored here, otherwise it will be null
    -- library_id BIGINT, -- WE MAY ADD IT (We should study that option first)
    -- competition_id BIGINT, -- WE MAY ADD IT (We should study that option first))
    -- time_table_id BIGINT, -- WE MAY ADD IT (We should study that option first))
    -- event_id BIGINT, -- WE MAY ADD IT (We should study that option first)
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (chat_id) REFERENCES mr_everything_chats(id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (assignment_questions_id) REFERENCES assignment_questions(id),
    FOREIGN KEY (quiz_questions_id) REFERENCES quiz_questions(id)
);



-- ==========================================================
-- NOTIFICATION - [FEATURE]
-- ==========================================================

CREATE TABLE user_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    user_id UUID NOT NULL,
    title VARCHAR(180) NOT NULL,
    body TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);